"""
RAGScope — Query API Router

Endpoints for RAG question-answering with citations and SSE streaming.
"""

import time
import uuid
import structlog

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.models import Query as QueryModel
from app.schemas.schemas import QueryRequest, QueryResponse, Citation
from app.retrieval.pipeline import RetrievalPipeline
from app.generation.generator import Generator
from app.observability.tracer import get_tracer, create_span

logger = structlog.get_logger()
router = APIRouter(prefix="/query", tags=["query"])
tracer = get_tracer("query")


@router.post("", response_model=QueryResponse)
async def query_rag(
    request: QueryRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    Ask a question — full RAG pipeline.
    
    Retrieves relevant chunks from the vector store, generates a grounded
    answer with inline citations, and returns with a trace_id for debugging.
    """
    start = time.perf_counter()
    trace_id = uuid.uuid4().hex[:16]

    with create_span(tracer, "rag_query", "CHAIN", {
        "query.text": request.question,
        "query.trace_id": trace_id,
    }):
        # ── 1. Retrieve ──────────────────────────
        retrieval_pipeline = RetrievalPipeline(db)
        chunks = await retrieval_pipeline.retrieve(
            query=request.question,
            top_k=request.top_k,
            use_hybrid=request.use_hybrid,
            use_reranker=request.use_reranker,
        )

        if not chunks:
            raise HTTPException(
                status_code=404,
                detail="No relevant documents found. Please ingest documents first.",
            )

        # ── 2. Generate ──────────────────────────
        generator = Generator()
        result = await generator.generate(
            question=request.question,
            chunks=chunks,
        )

        latency_ms = (time.perf_counter() - start) * 1000

        # ── 3. Store query record ─────────────────
        query_record = QueryModel(
            text=request.question,
            answer=result["answer"],
            citations=result["citations"],
            trace_id=trace_id,
            retrieval_scores=[
                {"chunk_id": c["chunk_id"], "dense_score": c.get("dense_score", 0)}
                for c in chunks
            ],
            latency_ms=round(latency_ms, 1),
            total_tokens=result.get("tokens_used"),
            config_snapshot={
                "top_k": request.top_k,
                "use_hybrid": request.use_hybrid,
                "use_reranker": request.use_reranker,
                "model": generator.model,
            },
        )
        db.add(query_record)
        await db.commit()

        logger.info(
            "RAG query complete",
            trace_id=trace_id,
            latency_ms=round(latency_ms, 1),
            chunks_used=len(chunks),
            citations=len(result["citations"]),
        )

        return QueryResponse(
            answer=result["answer"],
            citations=[Citation(**c) for c in result["citations"]],
            trace_id=trace_id,
            latency_ms=round(latency_ms, 1),
            tokens_used=result.get("tokens_used"),
        )


@router.post("/stream")
async def query_rag_stream(
    request: QueryRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    Ask a question with streaming response (SSE).
    
    Streams tokens as they're generated by the LLM.
    """
    # ── 1. Retrieve (non-streaming) ───────────
    retrieval_pipeline = RetrievalPipeline(db)
    chunks = await retrieval_pipeline.retrieve(
        query=request.question,
        top_k=request.top_k,
        use_hybrid=request.use_hybrid,
        use_reranker=request.use_reranker,
    )

    if not chunks:
        raise HTTPException(
            status_code=404,
            detail="No relevant documents found.",
        )

    # ── 2. Stream generation ──────────────────
    generator = Generator()

    async def event_stream():
        async for token_json in generator.generate_stream(
            question=request.question,
            chunks=chunks,
        ):
            yield f"data: {token_json}\n\n"
        yield "data: [DONE]\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
