"""
RAGScope — Contextual Retrieval

Implements the Anthropic contextual retrieval pattern:
Each chunk gets a short "context preamble" generated by an LLM
that explains how the chunk fits into the broader document.

This reduces retrieval failure by ~49% (Anthropic's benchmark)
because chunks carry their own context instead of losing it during splitting.

Reference: Anthropic, "Introducing Contextual Retrieval" (Sep 2024)
"""

import httpx
import structlog

from app.config import settings
from app.ingestion.chunkers.recursive_chunker import TextChunk
from app.observability.tracer import create_span, get_tracer

logger = structlog.get_logger()
tracer = get_tracer("ingestion")

CONTEXT_PROMPT = """Here is a document:
<document>
{doc_text}
</document>

Here is a chunk from that document:
<chunk>
{chunk_text}
</chunk>

Give a short succinct context (2-3 sentences) to situate this chunk within the overall document. This context will be prepended to the chunk for retrieval purposes. Respond with ONLY the context, no preamble."""


class ContextualEnricher:
    """
    Enriches chunks with contextual preambles.

    For each chunk, asks the LLM: "Explain how this chunk fits into
    the broader document." The result is prepended to the chunk content
    before embedding, dramatically improving retrieval precision.
    """

    def __init__(self):
        self.model = settings.ollama_model
        self.base_url = settings.ollama_base_url

    async def enrich_chunks(
        self,
        chunks: list[TextChunk],
        full_document_text: str,
    ) -> list[TextChunk]:
        """
        Add contextual preambles to each chunk.

        Args:
            chunks: List of text chunks to enrich
            full_document_text: The full document text for context

        Returns:
            Enriched chunks with preamble prepended to content
        """
        with create_span(
            tracer,
            "contextual_enrichment",
            "CHAIN",
            {
                "enrichment.chunk_count": len(chunks),
            },
        ):
            # Truncate document to fit in context window
            max_doc_length = 8000
            doc_preview = full_document_text[:max_doc_length]
            if len(full_document_text) > max_doc_length:
                doc_preview += "\n...[truncated]"

            enriched_chunks: list[TextChunk] = []

            async with httpx.AsyncClient(timeout=60.0) as client:
                for i, chunk in enumerate(chunks):
                    try:
                        prompt = CONTEXT_PROMPT.format(
                            doc_text=doc_preview,
                            chunk_text=chunk.content,
                        )

                        response = await client.post(
                            f"{self.base_url}/api/generate",
                            json={
                                "model": self.model,
                                "prompt": prompt,
                                "stream": False,
                                "options": {
                                    "temperature": 0.0,
                                    "num_predict": 200,
                                },
                            },
                        )
                        response.raise_for_status()
                        context = response.json().get("response", "").strip()

                        # Prepend context to chunk content
                        enriched_content = f"{context}\n\n{chunk.content}"

                        enriched_chunk = TextChunk(
                            content=enriched_content,
                            chunk_index=chunk.chunk_index,
                            token_count=max(1, len(enriched_content) // 4),
                            document_name=chunk.document_name,
                            element_type=chunk.element_type,
                            page_number=chunk.page_number,
                            section_path=chunk.section_path,
                            parent_content=chunk.parent_content,
                            metadata={
                                **chunk.metadata,
                                "contextual_enrichment": True,
                                "context_preamble": context,
                            },
                        )
                        enriched_chunks.append(enriched_chunk)

                        if (i + 1) % 20 == 0:
                            logger.info(
                                "Contextual enrichment progress",
                                done=i + 1,
                                total=len(chunks),
                            )

                    except Exception as e:
                        logger.warning(
                            "Context enrichment failed for chunk",
                            chunk_index=chunk.chunk_index,
                            error=str(e),
                        )
                        # Keep original chunk on failure
                        enriched_chunks.append(chunk)

            logger.info(
                "Contextual enrichment complete",
                total_chunks=len(enriched_chunks),
                enriched=sum(1 for c in enriched_chunks if c.metadata.get("contextual_enrichment")),
            )

            return enriched_chunks
